# Selection Key
SelectionKey=1234qweras
# Select candidate with arrow key
SelectCandidateWithArrowKey=True
# Page Size
PageSize=8
# Candidate List Layout
CandidateLayout=Vertical
# Use Keypad as Selection key
UseKeypadAsSelection=True
# Action when switching input method
SwitchInputMethodBehavior="Commit default selection"
# Add Phrase Forward
AddPhraseForward=False
# Backward phrase choice
ChoiceBackward=False
# Automatically shift cursor
AutoShiftCursor=True
# Enable easy symbol
EasySymbolInput=True
# Space as selection key
SpaceAsSelection=True
# Keyboard Layout
Layout="Default Keyboard"

